runtime: python39 # or the Python version you're using

entrypoint: gunicorn -b elevate.wsgi:application --host 127.0.0.1 --port 8000

# Handlers
handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

# Environment variables
env_variables:
  DJANGO_SETTINGS_MODULE: "elevate.settings"

# Optional: Configuring instance class
