<<<<<<< Updated upstream
# Generated by Django 4.2.7 on 2024-07-21 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.2.7 on 2024-07-20 12:09

from django.db import migrations, models
>>>>>>> Stashed changes


class Migration(migrations.Migration):
    initial = True

<<<<<<< Updated upstream
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
=======
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
>>>>>>> Stashed changes
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< Updated upstream
                ("personality", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chat_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.chatsession",
                    ),
                ),
=======
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
>>>>>>> Stashed changes
            ],
        ),
    ]
