# Generated by Django 4.2.7 on 2024-07-25 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0004_delete_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="timestamp",
        ),
    ]
