# Generated by Django 4.2.7 on 2024-07-27 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0006_history"),
    ]

    operations = [
        migrations.DeleteModel(
            name="History",
        ),
    ]
